### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [mgregoro/Crypt-Sodium#16]
Hi @mgregoro, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by mgregoro** [comment]
Hi @samuel-lucas6 -- I'd say it's fairly well maintained, yeah.  I still use it on several systems with newer versions of libsodium without issue.  

That said, I don't mind letting some of the other Perl bindings have their time in the sun.  Please go ahead and remove my library from the libsodium docs, thank you!

**Comment by samuel-lucas6** [comment]
Thanks for the reply. If you're sure, I'll go ahead and do that.

**Comment by mgregoro** [comment]
No problem!  Yes I'm sure, thank you.
