### ISSUE TITLE
Updating for newer libsodium ?

### ISSUE THREAD

**Issue by udf2457** [mgregoro/Crypt-Sodium#6]
Hi,

Do you have any plans to update for newer versions of libsodium ?  For example you don't appear to have implemented Argon2 based password hashing, looks like its still Scrypt based in your code ?

**Comment by mgregoro** [comment]
sure, are there other features in particular from newer versions you'd like me to take advantage of?

**Comment by udf2457** [comment]
Hi,

Thanks for getting back to me.

Yeah, apart from the Argon2 functions , the following would also certainly be very useful:

- Sealed Boxes (https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html)
- Crypto Boxes (https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html)
- XChaCha20-Poly1305 (https://download.libsodium.org/doc/secret-key_cryptography/xchacha20-poly1305_construction.html)
- AES GCM (https://download.libsodium.org/doc/secret-key_cryptography/aes-256-gcm.html)

Also, not essential, just looks interesting, Key Derivation from High-Entropy Keys (https://download.libsodium.org/doc/key_derivation/).

Good luck and thanks !

**Comment by mgregoro** [comment]
No problem.. the newest commit should have the Argon2 functionality as the default algo to `crypto_pwhash_*` .. I'll look into these other things and get them added.  Are you at all interested in an OO interface for some of this stuff?  I know there's another module that does it OO style so I've been trying to keep off their territory.. its just this huge long list is becoming tough to manage.  Thanks for the feedback and for using the module.

**Comment by mgregoro** [comment]
Also if you don't mind I'm going to break this into multiple issues..

**Comment by mgregoro** [comment]
Closing this; Argon2 access added, broke the rest into #7, #8, #9, #10, and #11.   Thanks again for your request.
